'reinit'
'open e:\shuzhi\huv.ctl'
'set t 1 '
'set grid off'
'set grads off'
'd h'
'enable print e:\shuzhi\initialh.gmf'
'print'
'disable'
'c'
'set t 2 '
'set grid off'
'set grads off'
'd h'
'enable print e:\shuzhi\predicth.gmf'
'print'
'disable'
'close 1'